export const MENU_ITEMS = [
  {
    id: 1,
    name: "Burger",
    category: "Main",
    price: 8.99,
    prepTime: "10 min",
    status: "Available",
    description: "Beef burger",
    image: "https://placehold.co/600x400", // Placeholder for the food image
  },
  {
    id: 2,
    name: "Pizza",
    category: "Main",
    price: 12.99,
    prepTime: "15 min",
    status: "Available",
    description: "Cheese pizza",
    image: "https://placehold.co/600x400",
  },
  {
    id: 3,
    name: "Fries",
    category: "Sides",
    price: 3.99,
    prepTime: "5 min",
    status: "Available",
    description: "Golden fries",
    image: "https://placehold.co/600x400",
  },
  {
    id: 4,
    name: "Fries",
    category: "Sides",
    price: 3.99,
    prepTime: "5 min",
    status: "Available",
    description: "Golden fries",
    image: "https://placehold.co/600x400",
  },
  {
    id: 5,
    name: "Fries",
    category: "Sides",
    price: 3.99,
    prepTime: "5 min",
    status: "Available",
    description: "Golden fries",
    image: "https://placehold.co/600x400",
  },
  {
    id: 6,
    name: "Fries",
    category: "Sides",
    price: 3.99,
    prepTime: "5 min",
    status: "Available",
    description: "Golden fries",
    image: "https://placehold.co/600x400",
  },
];
